### ISSUE TITLE
remove the limit of pair in cfg_sect_t%p

### ISSUE THREAD

**Issue by jubilee2** [pkgpl/cfgio#3]
My case requires reading a lot of data in ini file.
I changed the pair to dynamic array in cfg_sect_t
This way will be no upper limit of cfg_sect_t%p
If you like this change, please reply issue. I will create a merge request or you can create a merge request ahead.

**Comment by pkgpl** [comment]
Ok, please create a merge request. Thank you.

**Comment by pkgpl** [comment]
Thank you for your contribution.
Automatic array reallocation caused problems in my computer.
I used manual reallocation instead.

**Comment by jubilee2** [comment]
sorry not test in intel fortran environment.   thanks you for fix issue
