### ISSUE TITLE
default value for arrays

### ISSUE THREAD

**Issue by markusgo** [pkgpl/cfgio#6]
hello! I have come about a problem using this library.
I can't seem to be able to define a default content for an array. Don't give it a value in another section it ends saying it cannot find the respective key.

Example:
.................

[DEFAULTS]
a = 1,2,3

[Section 1]

...............

a is an allocatable array. Also tried introducing a variable with the desired number of elements in a and allocate it manually but i still get the same error.

**Comment by pkgpl** [comment]
Thank you.
I fixed it.
See `test/test_array.f90`, `test/test_array.cfg`.

**Comment by markusgo** [comment]
Great work. Thank you!
